server:
  port: 8084

spring:
   redis:
      database: 0
      host: 47.104.19.44
      port: 6379
      password: 123456
      #cluster:
       # nodes: #使用nodes时不用使用host
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 7 # 连接池中的最小空闲连接
        timeout: 5000 # 连接超时时间（毫秒）
        commandTimeout: 5000
        maxAttempts: 10000 #重试时间